#!/bin/sh
TARGET_IP="$1"

[ -z "$TARGET_IP" ] && echo "missing ip" && exit 1

ssh -i /home/adam/.ssh/blocker_key blocker@10.0.0.48 "
if
 sudo iptables -L INPUT -n | grep -q $TARGET_IP; then echo 'IP already blocked: $TARGET_IP'
else 
 sudo iptables -I INPUT 1 -s $TARGET_IP -j DROP 
 echo 'Blocked $TARGET_IP on 10.0.0.48'
fi
"
